version: "3"

services:

  mongo:
    image: mongo
    hostname: mongo
    restart: always
    ports:
      - "29564:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pa55word #use mitsborn_default as network

  library-database:
      image: postgres:16.2-alpine3.19
      environment:
        - POSTGRES_USER=library-user
        - POSTGRES_PASSWORD=libraryPassPostgresql1
        - POSTGRES_DB=libraryDb
      ports:
        - "12965:5432"
      restart: always

  kafka-cluster:
      image: landoop/fast-data-dev:latest
      hostname: kafka
      restart: always
      environment:
        ADV_HOST: 127.0.0.1
        RUNTESTS: 0
        FORWARDLOGS: 0
        SAMPLEDATA: 0
      ports:
        - "2181:2181"                 # Zookeeper port
        - "3030:3030"                 # Landoop UI port
        - "8081-8083:8081-8083"       # REST Proxy, Schema Registry, Kafka Connect ports
        - "9581-9585:9581-9585"       # JMX Ports
        - "11296:9092"                 # Kafka Broker port